services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token
      - key: CHAT_ID
        value: -1001234567890
    build:
      pythonVersion: 3.11.8
